### ISSUE TITLE
Gradle Support

### ISSUE THREAD

**Issue by galex** [LogentriesCommunity/le_android#10]
Hello,

Are you planning to deploy the SDK to Central Maven repository to be able to import it by gradle as everybody switches to Android Studio?

Regards,
Alex

**Comment by anti43** [comment]
Hello,
any plans on this yet?

Regards,

Andreas

**Comment by nister** [comment]
Hi Guys,
really waiting for android lib on Maven repository

Regards,
Roman

**Comment by liutingdu** [comment]
Would be nice to see it on Maven/Gradle :)

Tried to use [JitPack](https://jitpack.io/#logentries/le_android) but seems the repo is not tagged for versions yet..

Thanks!

**Comment by sguillen** [comment]
Upvote!

**Comment by jitpack-io** [comment]
@liutingdu Although there is no tag, you can use the latest commit hash as the version:
https://jitpack.io/#logentries/le_android/5294e11d2f

A GitHub release would be nice though!

**Comment by StephenHynes7** [comment]
We have a new release incoming which should at least start to get the ball rolling here

**Comment by luksfarris** [comment]
Thank you Stephen! Looking forward to it

**Comment by cosminstefanxp** [comment]
:+1:

**Comment by driveorphone** [comment]
Any update on Gradle support ? 🎱

**Comment by amadib** [comment]
Are there any updates regarding this issue?

**Comment by mendozamiche** [comment]
@StephenHynes7 Any update on that release?

**Comment by andreagrandi** [comment]
@StephenHynes7 hi, any update on this issue? Thanks

**Comment by StephenHynes7** [comment]
Unfortunately this project has fallen by the way side and we are not actively developing it at the moment. I think we will be looking into helping getting the community involved here more.

**Comment by andreagrandi** [comment]
@udangel-r7 why are you closing this one? Thanks

**Comment by udangel-r7** [comment]
we are currently not actively developing/maintaining this library. that means we are currently also not planning to publish or release this library to places like maven central or add additional support to gradle
