### ISSUE TITLE
IOException is never thrown if we can not connect to Logentries

### ISSUE THREAD

**Issue by StephenHynes7** [LogentriesCommunity/le_android#15]
>
I'd like to report a bug in the Android code. At this line (https://github.com/logentries/le_android/blob/master/src/main/java/com/logentries/android/LogentriesAndroid.java#L143), all exceptions are caught, and therefore IOException is never thrown if there is an issue with establishing the socket connection to LogEntries. Consequently, the IOException that would have been thrown thrown is not caught here (https://github.com/logentries/le_android/blob/master/src/main/java/com/logentries/android/LogentriesAndroid.java#L164), making the reopen process think it succeeded when in fact it had not. Consequently the SocketAppender tries to write to the socket again and ends up throwing a separate exception, ending up here (https://github.com/logentries/le_android/blob/master/src/main/java/com/logentries/android/LogentriesAndroid.java#L232) and causing the SocketAppender to stop running.
>
I resolved this in my own code by catching and throwing the initial IOException. Just wanted to let you guys know!

**Comment by StephenHynes7** [comment]
@michael-seibert-le if you fancy taking a look at this let me know :)

**Comment by MarkLC** [comment]
@StephenHynes7 want to contribute the fix if you've already done it locally? save us doing it twice

**Comment by StephenHynes7** [comment]
Its a copy paste from a user :)

-----Original Message-----

**Comment by MarkLC** [comment]
Ah. Do they want to contribute?  :D
