### ISSUE TITLE
le_android not compatible with Android Marshmallow API 23 - org.apache.http is deprecated

### ISSUE THREAD

**Issue by jedi4ever** [LogentriesCommunity/le_android#26]
Starting from API 23 org.apache.http is deprecated
<http://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client>

_Quick fix:_
If you are using a recent gradle

```android {
    useLibrary 'org.apache.http.legacy' // Need until GMS upgraded
}```

Or else copy the lib that is included within the sdk into your project

`cp /Applications/android-sdk-macosx/platforms/android-23/optional/org.apache.http.legacy.jar app/libs/``

_Permanent fix:_
rewrite le_android to use httpConnection & co.

I'm leaving this issue here for info & tracking the progress

**Comment by amadib** [comment]
is this scheduled to be done as well?

**Comment by amadib** [comment]
After upgrading the application is no longer useable 

    D  java.lang.IllegalArgumentException: 'httpPost' parameter cannot be set to true if 'useSsl' is set to true.
    D      at com.logentries.net.LogentriesClient.<init>(LogentriesClient.java:63)
    D      at com.logentries.logger.AsyncLoggingWorker$SocketAppender.openConnection(AsyncLoggingWorker.java:187)
    D      at com.logentries.logger.AsyncLoggingWorker$SocketAppender.reopenConnection(AsyncLoggingWorker.java:204)
    D      at com.logentries.logger.AsyncLoggingWorker$SocketAppender.run(AsyncLoggingWorker.java:269)

**Comment by jedi4ever** [comment]
@udangel-r7 what do mean with needs contribution wontfix ?

**Comment by udangel-r7** [comment]
le_android is no longer actively maintained by Logentries. In order for this issue to be addressed, we would need to get contributions. 

I closed this issue and marked it with wontfix to make it clear that we will not work on this.

If you think leaving it open and marking it only with needs contribution is the better way forward please let me know
