### ISSUE TITLE
Log entries crashes while trying to log.

### ISSUE THREAD

**Issue by humblerookie** [LogentriesCommunity/le_android#44]
This keeps crashing on production with a few users.

http://crashes.to/s/8d329521e82

**Comment by andreagrandi** [comment]
I'm having exactly the same problem and I can reproduce it every time. Basically I create an instance of the logger in the main activity. Then I create another instance in a dialog activity. When I go back to the main activity, the next thing I try to log will make the application crash.

**Comment by andreagrandi** [comment]
@udangel-r7 hi, could you please give us more information about why you are closing the bug? Has it been resolved? Thanks

**Comment by udangel-r7** [comment]
This project is no longer under actively maintained. Leaving the issues open indicates that somebody is somehow working on it. I'll label everything as wont-fix and need-support
