### ISSUE TITLE
Sending logs via HTTPS

### ISSUE THREAD

**Issue by samhandev** [LogentriesCommunity/le_android#46]
According to this page:
https://docs.logentries.com/docs/http-post
Sending logs via HTTPS should still be supported.

It seems PR #40 removed this functionality but I was wondering if this is still the case?

Does it matter which end point we send the logs to?

`http://js.logentries.com/v1/logs/` vs `https://webhook.logentries.com/noformat/logs/LOG-TOKEN`

@mrud @cheffernan-r7 @pclune-r7 would be good to get some feedback on this if possible as I know this library is no longer supported.

Thanks,
Sam

**Comment by udangel-r7** [comment]
You can connect and use both endpoints via http or https. After looking into #40 itself it seems that https support itself was removed, however data is send in via TLS over port 443 per default.

We still are accepting pull requests / contributions to the library.

**Comment by samhandev** [comment]
PR #48 implements this so this issue can be closed
