### ISSUE TITLE
Can't download the Android Library

### ISSUE THREAD

**Issue by andreykadatsky** [LogentriesCommunity/le_android#49]
https://github.com/LogentriesCommunity/le_android/raw/master/lib - 404 error

**Comment by udangel-r7** [comment]
How and where did you get this url? we do not publish artifacts via this git repository

**Comment by andreykadatsky** [comment]
Few places refers to this location: 
1) https://logentries.com/app/02b5fa82#/add-log/android - "Install The Android Library" - "Download the Android Library here and place it in the /lib folder of your Android project"
2) On https://github.com/LogentriesCommunity/le_android - `Setup` chapter, `Next, download the library jar file here and place it in the /yourProject/libs folder of your Android project.`

**Comment by MZein1292** [comment]
Where else can we download the library from since both the site and github repo have broken download url.

**Comment by auschmann** [comment]
So where do we download the jar?
We would like to evaluate logentry...
Can not be too hard to provide the needed library or?

**Comment by StephenHynes7** [comment]
Can you try here https://github.com/LogentriesCommunity/le_android/blob/master/logentries-android.jar ?

**Comment by andreykadatsky** [comment]
Thats work , thanks.
