### ISSUE TITLE
Android app - logentries logger stops to log on reassociating wifi

### ISSUE THREAD

**Issue by coolgandhi** [LogentriesCommunity/le_android#6]
We have an Android app with a scenario which requires us to programmatically re-associate the wifi on the device once every day. We use logentries for our logging solution. I observe that after the wifi gets re-associated through the app, logentries stops logging. I looked at the debug log and see this message: "Asynchronous socket writer interrupted" I hoped that the logentries client would recover and continue to log.

Also, if the device goes out of range from wifi (i took it out of range for about 25-30 mts) and comes back to it, logentries doesn't seem to recover and restart the logging.

Please advise on some options which I could consider that I may have missed which the library api offers?

Thanks!

**Comment by udangel-r7** [comment]
this project is no longer officially maintained. closing.

**Comment by kibotu** [comment]
> this project is no longer officially maintained. closing.
hang on, did i miss something? no offence but logentries is not exactly a cheap service, how do they expect everyone to use their website if not using this library?
