### ISSUE TITLE
AndroidLogger; NoSuchMethodError: java.lang.String.getBytes

### ISSUE THREAD

**Issue by gervaisb** [LogentriesCommunity/le_android#8]
Each time my app try to log on LogEntries via AndroidLogger I receive the following exception :
```java
java.lang.NoSuchMethodError: java.lang.String.getBytes
  at com.logentries.android.LogentriesAndroid$SocketAppender.run(LogentriesAndroid.java:206)
```

My test device run on Android 2.1 (Api 7)

**Comment by lucasddaniel** [comment]
Thanks gervaisb for your tip! I'm with the same problem ;)
